services:
  - type: web
    name: obscura-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: TMDB_API_KEY
        sync: false